### ISSUE TITLE
Using breadcrumbs with domain routes

### ISSUE THREAD

**Issue by craigharman** [Artian-Techs/adonis-breadcrumbs#1]
I am trying to use adonis-breadcrumbs when my routes are limited by domains as per https://docs.adonisjs.com/guides/basics/routing#registering-routes-for-a-specific-domain

If I try to access breadcrumbs with `breadcrumbs.get()` I receive an error `Cannot lookup route`. I assume this is because the route lookup needs to include the domain details. 

Is there a way to do this?

**Comment by Melchyore** [comment]
Hey! 👋

Can you please create a reproduction repository?

**Comment by Melchyore** [comment]
I was able to reproduce the issue on my own. I'll work on it and publish a new version. Thank you!

**Comment by Melchyore** [comment]
Please update to the latest version, it should work now.
